### PR TITLE
fix: update package name to match main noir repo

### LINKED ISSUE #19: nightly build failed
Something broke our nightly builds.

Check the [build](https://github.com/noir-lang/build-nargo/actions/runs/4624761794) workflow for details.

This issue was raised by the workflow `build-x86_64-pc-windows-wasm`

### PR DESCRIPTION
**Pull request by TomAFrench**
This PR updates the build command to match https://github.com/noir-lang/noir/pull/1065

closes #19

### CODE REVIEW

**Comment by phated** [comment]
@TomAFrench did other stuff change? It seems the commands aren't working now.

**Comment by TomAFrench** [comment]
The only changes were the splitting of the `nargo` crate (and the followup changes to feature flags) I don't think that could result in the error message we're seeing.

**Comment by TomAFrench** [comment]
Pending https://github.com/noir-lang/noir/pull/1091

**Review by kobyhallx — APPROVED** [review]
👍

**Pull request merged**
